### ISSUE TITLE
不支持Java8

### ISSUE THREAD

**Issue by iyutong** [xiaoyvyv/JavaCompileEngine#1]
不支持Java8，嘤嘤嘤

**Comment by xiaoyvyv** [comment]
Java 8 语法是可以编译运行的，需要替换 rt.jar 为 jdk 8 安装目录内的 rt.jar（60多M那个），需要自己精简

**Comment by xiaoyvyv** [comment]
更新了 compile-d8 支持 jdk8 语法了
