### ISSUE TITLE
Scanner输入两次问题

### ISSUE THREAD

**Issue by NITU233** [xiaoyvyv/JavaCompileEngine#2]
![Screenshot_20220406_004305_com xiaoyv javaengine](https://user-images.githubusercontent.com/102815148/161804452-ceb62f41-8dfe-4777-a8fe-aeaec0faaac8.jpg)
Scanner使用两次nextLine会出现方块该怎么解决

**Comment by xiaoyvyv** [comment]
1.0.4 已修复
